# Generated by Django 4.1.7 on 2023-07-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('breed', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
