# Generated by Django 4.1.7 on 2023-07-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_catsforpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcats',
            name='image',
            field=models.ImageField(blank=True, upload_to='cat/'),
        ),
    ]
