# Generated by Django 4.1.7 on 2023-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_alter_balance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcats',
            name='cost',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
